Traceback (most recent call last):
  File "/home/goodpast/graha682/code/python/freeze_and_thaw/cython/cmain.py", line 6, in <module>
    main.main(sys.argv[1])
  File "main.pyx", line 48, in main.main (main.c:2558)
    
  File "read_input.pyx", line 85, in read_input.read_input (read_input.c:2394)
    # read the input filename
  File "/home/goodpast/graha682/.local/lib/python2.7/site-packages/input_reader/input_reader.py", line 88, in read_input
    i, namespace = self._parse_key_level(f, 0)
  File "/home/goodpast/graha682/.local/lib/python2.7/site-packages/input_reader/key_adder.py", line 542, in _parse_key_level
    i, namespace = self._find_keys_in_input(f, i, namespace)
  File "/home/goodpast/graha682/.local/lib/python2.7/site-packages/input_reader/key_adder.py", line 566, in _find_keys_in_input
    raise ReaderError (self.name+': '+str(e))
input_reader.helpers.ReaderError: main: main: Unrecognized key: "readchk"
